# Generated by Django 5.0.14 on 2026-03-13 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DiagnosticSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("filename", models.CharField(default="untitled", max_length=255)),
                ("language", models.CharField(default="plaintext", max_length=50)),
                ("code", models.TextField(blank=True, default="")),
                ("issue", models.TextField(blank=True, default="")),
                ("concept_gap", models.TextField(blank=True, default="")),
                ("suggestion", models.TextField(blank=True, default="")),
                (
                    "concept_tag",
                    models.CharField(blank=True, default="", max_length=80),
                ),
                ("confidence_score", models.IntegerField(default=0)),
                (
                    "confidence_label",
                    models.CharField(blank=True, default="", max_length=40),
                ),
                ("loop_count", models.IntegerField(default=0)),
                ("conditional_count", models.IntegerField(default=0)),
                ("function_like_count", models.IntegerField(default=0)),
                ("max_tree_depth", models.IntegerField(default=0)),
                ("max_loop_nesting", models.IntegerField(default=0)),
                ("fix_now", models.TextField(blank=True, default="")),
                ("learn_now", models.TextField(blank=True, default="")),
                ("practice_now", models.TextField(blank=True, default="")),
            ],
        ),
        migrations.CreateModel(
            name="LearnerAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("action_type", models.CharField(max_length=80)),
                ("filename", models.CharField(blank=True, default="", max_length=255)),
                ("language", models.CharField(blank=True, default="", max_length=50)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "snapshot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actions",
                        to="logiclens.diagnosticsnapshot",
                    ),
                ),
            ],
        ),
    ]
