# Generated by Django 5.0.14 on 2026-03-14 00:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logiclens", "0003_note"),
    ]

    operations = [
        migrations.AddField(
            model_name="diagnosticsnapshot",
            name="profile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="snapshots",
                to="logiclens.userprofile",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="badges",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="current_streak",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="last_activity_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
